info:
  name: MiniGames
  author: Ultra119
  version: 1.1
  description: Some stupid minigames collection
  src_url: https://github.com/PBModular/MiniGames
  python: 3.13

permissions:
  - require_db
